### ISSUE TITLE
image not running, user anduril cannot read init.sh

### ISSUE THREAD

**Issue by moonq** [Gig77/anduril-moksiskaan#1]
HI, 

I could not run the current docker image, since /home/anduril/init.sh lacks read access to the user anduril.

it can be fixed for sure, by adding a line

```
...
COPY init.sh /home/anduril/init.sh
RUN chmod 777 /home/anduril/init.sh
ENTRYPOINT ["/home/anduril/init.sh"]
```

I also found it useful to allow postgresql access from outside the container:

```

RUN echo 'host all all 0.0.0.0/0 trust' >> /etc/postgresql/9.1/main/pg_hba.conf
RUN sed -i "s/^#.*listen_addresses.*/listen_addresses = '*'/" /etc/postgresql/9.1/main/postgresql.conf

```

Are you planning to update the database anytime?  we can do testing etc if that helps..

**Comment by Gig77** [comment]
Thanks, fixed. This image will almost certainly not get any more updates, but I might put up another one based on Anduril2, depending on if/when Moksiskaan is migrated to Anduril2. I will meet Marko Laakso in a couple of weeks to clarify that.
